import { describe, expect, it } from "vitest";
import { assessGenesisServerSmoke } from "./server-smoke.js";

describe("Genesis server smoke assessment", () => {
  it("marks smoke as progressed when tick and pump both advance", () => {
    const assessment = assessGenesisServerSmoke({
      societySummary: {
        world: null,
        tickState: {
          version: 1,
          runCount: 1,
          skipCount: 0,
          idleStreak: 0,
          updatedAt: 100,
        },
        experimentSignals: {
          defaultMinIntervalMs: 0,
          defaultMaxTicks: 2,
          defaultMaxActions: 2,
          defaultMaxRounds: 2,
          defaultMaxFailureRounds: 1,
          defaultMaxStableRounds: 1,
          nextPlanSkillEvolutionBias: 1.25,
          amplificationScore: 1.5,
          runawayRiskScore: 2.4,
          phaseState: "amplifying",
        },
        focusSummary: {
          activeFocusCount: 0,
          activeLineageCount: 0,
          topFocusedLineages: [],
        },
        ecologyCounts: {
          active: 1,
          stressed: 0,
          dormant: 0,
          extinct: 0,
        },
        collaborationSummary: {
          activePlanCount: 1,
          collaborativePlanCount: 1,
          emergencyPlanCount: 1,
          forcedCollaborationPlanCount: 1,
          highCoveragePlanCount: 0,
          mobilizedAgentCount: 2,
          averageMobilizedCoverageRatio: 0.67,
          averageTargetCoverageRatio: 0.8,
          leadAssignmentCount: 1,
          supportAssignmentCount: 1,
          reviveAssignmentCount: 0,
          productiveMobilizedLineageCount: 2,
          productiveLeadLineageCount: 1,
          productiveSupportLineageCount: 1,
          productiveReviveLineageCount: 0,
          productiveAssignmentCoverageRatio: 1,
          leadYieldScore: 2,
          supportYieldScore: 1.5,
          reviveYieldScore: 0,
          queuedAssignmentCount: 2,
          averageAssignmentsPerPlan: 2,
          coordinationScore: 6,
          collaborationEffectScore: 10.5,
        },
        vitalitySummary: {
          lineageCount: 2,
          childLineageCount: 1,
          specialtyOnlyChildCount: 1,
          superpowerChildCount: 0,
          specialtyWorkingChildCount: 1,
          specialtyProactiveChildCount: 0,
          specialtyChildPublicValue: 0.6,
          superpowerWorkingChildCount: 0,
          superpowerProactiveChildCount: 0,
          superpowerChildPublicValue: 0,
          replicatingParentCount: 1,
          maxChildrenPerParent: 1,
          workingLineageCount: 2,
          childWorkingLineageCount: 1,
          replicatingWorkingParentCount: 1,
          heartbeatLineageCount: 1,
          proactiveReadyLineageCount: 1,
          proactiveWorkingLineageCount: 1,
          activeFocusLineageCount: 1,
          activeTriggerCount: 1,
          recentCapturedSkillCount: 1,
          recentDerivedSkillCount: 1,
          totalPublicValue: 2.5,
          totalPrivateValue: 1,
          totalSurvivalCredit: 2.5,
          totalExpansionCredit: 1.2,
          proactiveSignalScore: 4,
          autonomousExpansionScore: 4.7,
          founderRoleCoverageCount: 0,
          founderYieldCoverageCount: 0,
          roleAlignedWorkingLineageCount: 0,
          roleAlignedProactiveLineageCount: 0,
          roleAlignedProactiveYieldScore: 0,
          proactiveSpecializationScore: 0,
          founderRoleBreakdown: [],
          topParentLineages: [{ lineageId: "main", childCount: 1, ecologyState: "active" }],
        },
        activeDispatchCount: 1,
        reviveDispatchCount: 0,
        activePlans: [],
        coordinationQueue: [],
        coordinationBatches: [],
        topLineages: [],
      },
      seededPlan: {
        primarySessionKey: "agent:main:main",
      },
      tick: {
        decision: "ran",
      },
      postTickSociety: {
        summary: {
          world: null,
          tickState: {
            version: 2,
            runCount: 2,
            skipCount: 0,
            idleStreak: 0,
            updatedAt: 101,
          },
          experimentSignals: {
            defaultMinIntervalMs: 0,
            defaultMaxTicks: 2,
            defaultMaxActions: 2,
            defaultMaxRounds: 2,
            defaultMaxFailureRounds: 1,
            defaultMaxStableRounds: 1,
            nextPlanSkillEvolutionBias: 1.4,
            amplificationScore: 1.8,
            runawayRiskScore: 2.8,
            phaseState: "amplifying",
          },
          focusSummary: {
            activeFocusCount: 0,
            activeLineageCount: 0,
            topFocusedLineages: [],
          },
          ecologyCounts: {
            active: 1,
            stressed: 0,
            dormant: 0,
            extinct: 0,
          },
          collaborationSummary: {
            activePlanCount: 1,
            collaborativePlanCount: 1,
            emergencyPlanCount: 1,
            forcedCollaborationPlanCount: 1,
            highCoveragePlanCount: 0,
            mobilizedAgentCount: 2,
            averageMobilizedCoverageRatio: 0.67,
            averageTargetCoverageRatio: 0.8,
            leadAssignmentCount: 1,
            supportAssignmentCount: 1,
            reviveAssignmentCount: 0,
            productiveMobilizedLineageCount: 2,
            productiveLeadLineageCount: 1,
            productiveSupportLineageCount: 1,
            productiveReviveLineageCount: 0,
            productiveAssignmentCoverageRatio: 1,
            leadYieldScore: 2.25,
            supportYieldScore: 1.75,
            reviveYieldScore: 0,
            queuedAssignmentCount: 2,
            averageAssignmentsPerPlan: 2,
            coordinationScore: 6.5,
            collaborationEffectScore: 11,
          },
          vitalitySummary: {
            lineageCount: 2,
            childLineageCount: 1,
            specialtyOnlyChildCount: 1,
            superpowerChildCount: 0,
            specialtyWorkingChildCount: 1,
            specialtyProactiveChildCount: 0,
            specialtyChildPublicValue: 0.6,
            superpowerWorkingChildCount: 0,
            superpowerProactiveChildCount: 0,
            superpowerChildPublicValue: 0,
            replicatingParentCount: 1,
            maxChildrenPerParent: 1,
            workingLineageCount: 2,
            childWorkingLineageCount: 1,
            replicatingWorkingParentCount: 1,
            heartbeatLineageCount: 1,
            proactiveReadyLineageCount: 1,
            proactiveWorkingLineageCount: 1,
            activeFocusLineageCount: 1,
            activeTriggerCount: 1,
            recentCapturedSkillCount: 2,
            recentDerivedSkillCount: 1,
            totalPublicValue: 3,
            totalPrivateValue: 1.25,
            totalSurvivalCredit: 3,
            totalExpansionCredit: 1.4,
            proactiveSignalScore: 4.5,
            autonomousExpansionScore: 4.9,
            founderRoleCoverageCount: 0,
            founderYieldCoverageCount: 0,
            roleAlignedWorkingLineageCount: 0,
            roleAlignedProactiveLineageCount: 0,
            roleAlignedProactiveYieldScore: 0,
            proactiveSpecializationScore: 0,
            founderRoleBreakdown: [],
            topParentLineages: [{ lineageId: "main", childCount: 1, ecologyState: "active" }],
          },
          activeDispatchCount: 1,
          reviveDispatchCount: 0,
          activePlans: [],
          coordinationQueue: [],
          coordinationBatches: [],
          topLineages: [],
        },
      },
      pump: {
        ticks: [{}, {}],
      },
      followupPump: {
        ticks: [{}],
      },
      probePumps: [
        {
          pump: { ticks: [{}] },
          summary: {
            summary: {
              world: null,
              tickState: {
                version: 5,
                runCount: 6,
                skipCount: 0,
                idleStreak: 0,
                updatedAt: 104,
              },
              experimentSignals: {
                defaultMinIntervalMs: 0,
                defaultMaxTicks: 4,
                defaultMaxActions: 3,
                defaultMaxRounds: 3,
                defaultMaxFailureRounds: 2,
                defaultMaxStableRounds: 2,
                nextPlanSkillEvolutionBias: 1.8,
                amplificationScore: 2.4,
                runawayRiskScore: 3.55,
                phaseState: "amplifying",
              },
              focusSummary: {
                activeFocusCount: 0,
                activeLineageCount: 0,
                topFocusedLineages: [],
              },
              ecologyCounts: {
                active: 1,
                stressed: 0,
                dormant: 0,
                extinct: 0,
              },
              collaborationSummary: {
                activePlanCount: 1,
                collaborativePlanCount: 1,
                emergencyPlanCount: 1,
                forcedCollaborationPlanCount: 1,
                highCoveragePlanCount: 1,
                mobilizedAgentCount: 3,
                averageMobilizedCoverageRatio: 1,
                averageTargetCoverageRatio: 0.8,
                leadAssignmentCount: 1,
                supportAssignmentCount: 1,
                reviveAssignmentCount: 1,
                productiveMobilizedLineageCount: 3,
                productiveLeadLineageCount: 1,
                productiveSupportLineageCount: 1,
                productiveReviveLineageCount: 1,
                productiveAssignmentCoverageRatio: 1,
                leadYieldScore: 3,
                supportYieldScore: 2.2,
                reviveYieldScore: 1.3,
                queuedAssignmentCount: 3,
                averageAssignmentsPerPlan: 3,
                coordinationScore: 9,
                collaborationEffectScore: 15.25,
              },
              vitalitySummary: {
                lineageCount: 4,
                childLineageCount: 2,
                specialtyOnlyChildCount: 1,
                superpowerChildCount: 1,
                pressureAmplifiedSuperpowerChildCount: 1,
                pressureAmplifiedSuperpowerWorkingChildCount: 1,
                specialtyWorkingChildCount: 1,
                specialtyProactiveChildCount: 0,
                specialtyChildPublicValue: 0.5,
                specialtyChildYieldEfficiency: 0.5,
                specialtyChildSustainedValueScore: 0.5,
                superpowerWorkingChildCount: 1,
                superpowerProactiveChildCount: 1,
                superpowerChildPublicValue: 0.65,
                superpowerChildYieldEfficiency: 0.9,
                superpowerChildSustainedValueScore: 1.15,
                childYieldLeader: "superpower",
                childYieldEfficiencyGap: 0.4,
                multiGenerationLineageCount: 3,
                secondGenerationChildCount: 2,
                thirdGenerationChildCount: 1,
                deepestGenerationDepth: 3,
                multiGenerationWorkingChildCount: 3,
                multiGenerationProactiveChildCount: 2,
                multiGenerationSuperpowerChildCount: 2,
                multiGenerationPublicValue: 1.5,
                multiGenerationYieldEfficiency: 0.67,
                multiGenerationSustainedValueScore: 2.5,
                multigenerationFounderCount: 1,
                highestMultigenerationFounderOrigin: "builder",
                highestMultigenerationFounderScore: 2.75,
                multiGenerationLeaders: [
                  {
                    founderOrigin: "builder",
                    deepestGenerationDepth: 3,
                    secondGenerationChildCount: 2,
                    thirdGenerationChildCount: 1,
                    multiGenerationChildCount: 3,
                    multiGenerationWorkingChildCount: 3,
                    multiGenerationProactiveChildCount: 2,
                    multiGenerationSuperpowerChildCount: 2,
                    multiGenerationValueScore: 2.75,
                    multiGenerationYieldEfficiency: 0.67,
                  },
                ],
                climateReplicationPressureScore: 3.8,
                survivalReplicationPressureScore: 1.2,
                productiveReplicationCapacityScore: 5.7,
                replicationFrequencyScore: 4,
                replicationTriggerFrequencyScore: 3.25,
                replicationSuccessFrequencyScore: 3.5,
                averageReplicationLatency: 1.5,
                replicationSpeedScore: 5.5,
                climatePressuredChildCount: 2,
                climatePressuredSuperpowerChildCount: 1,
                climatePressuredChildValueScore: 2.6,
                climateSpecialtyWorkingChildCount: 1,
                climateSpecialtyProactiveChildCount: 0,
                climateSpecialtyChildPublicValue: 0.5,
                climateSpecialtyChildYieldEfficiency: 0.5,
                climateSpecialtyChildSustainedValueScore: 0.5,
                climateSuperpowerWorkingChildCount: 1,
                climateSuperpowerProactiveChildCount: 1,
                climateSuperpowerChildPublicValue: 0.65,
                climateSuperpowerChildYieldEfficiency: 0.9,
                climateSuperpowerChildSustainedValueScore: 1.15,
                climateChildYieldLeader: "superpower",
                climateChildYieldEfficiencyGap: 0.4,
                survivalPressuredChildCount: 1,
                survivalPressuredSuperpowerChildCount: 1,
                survivalPressuredChildValueScore: 1.4,
                survivalSpecialtyWorkingChildCount: 0,
                survivalSpecialtyProactiveChildCount: 0,
                survivalSpecialtyChildPublicValue: 0,
                survivalSpecialtyChildYieldEfficiency: 0,
                survivalSpecialtyChildSustainedValueScore: 0,
                survivalSuperpowerWorkingChildCount: 1,
                survivalSuperpowerProactiveChildCount: 1,
                survivalSuperpowerChildPublicValue: 0.65,
                survivalSuperpowerChildYieldEfficiency: 0.9,
                survivalSuperpowerChildSustainedValueScore: 1.15,
                survivalChildYieldLeader: "superpower",
                survivalChildYieldEfficiencyGap: 0.9,
                climateResponsiveReplicationParentCount: 1,
                survivalResponsiveReplicationParentCount: 1,
                proactiveReplicationParentCount: 1,
                collaborativeExpansionFounderCount: 2,
                crossFounderExpansionLinkCount: 1,
                crossFounderExpansionScore: 4,
                cooperativeYieldFounderCount: 2,
                leadCooperationFounderCount: 1,
                highestLeadCooperationFounderOrigin: "builder",
                highestLeadCooperationFounderScore: 4.5,
                supportCooperationFounderCount: 1,
                highestSupportCooperationFounderOrigin: "creator",
                highestSupportCooperationFounderScore: 2.75,
                reviveCooperationFounderCount: 1,
                highestReviveCooperationFounderOrigin: "negotiator",
                highestReviveCooperationFounderScore: 3.1125,
                highestCollaborationInfluenceFounderOrigin: "builder",
                highestCollaborationInfluenceFounderScore: 3.5,
                highestCooperativeYieldFounderOrigin: "builder",
                highestCooperativeYieldFounderScore: 5.9375,
                highestExpansionInfluenceFounderOrigin: "builder",
                highestExpansionInfluenceFounderScore: 3.25,
                expansionLinkLeaders: [
                  {
                    founderOrigin: "builder",
                    linkedFounderCount: 1,
                    collaborativeChildCount: 2,
                    linkedExpansionScore: 3.25,
                    linkedFounders: ["creator"],
                  },
                ],
                collaborationInfluenceLeaders: [
                  {
                    founderOrigin: "builder",
                    linkedFounderCount: 1,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedProactiveYieldScore: 3,
                    collaborationInfluenceScore: 3.5,
                  },
                  {
                    founderOrigin: "creator",
                    linkedFounderCount: 1,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedProactiveYieldScore: 2,
                    collaborationInfluenceScore: 3.25,
                  },
                  {
                    founderOrigin: "scout",
                    linkedFounderCount: 0,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedProactiveYieldScore: 2.3,
                    collaborationInfluenceScore: 1.825,
                  },
                ],
                cooperativeYieldLeaders: [
                  {
                    founderOrigin: "builder",
                    linkedFounderCount: 1,
                    roleAlignedProactiveYieldScore: 3,
                    linkedExpansionScore: 3.25,
                    cooperativeYieldScore: 5.9375,
                  },
                  {
                    founderOrigin: "creator",
                    linkedFounderCount: 1,
                    roleAlignedProactiveYieldScore: 2,
                    linkedExpansionScore: 1.25,
                    cooperativeYieldScore: 3.4375,
                  },
                ],
                leadCooperationLeaders: [
                  {
                    founderOrigin: "builder",
                    leadAssignmentCount: 1,
                    leadYieldScore: 3,
                    leadCooperationScore: 4.5,
                  },
                ],
                supportCooperationLeaders: [
                  {
                    founderOrigin: "creator",
                    supportAssignmentCount: 1,
                    supportYieldScore: 2,
                    supportCooperationScore: 2.75,
                  },
                ],
                reviveCooperationLeaders: [
                  {
                    founderOrigin: "negotiator",
                    reviveAssignmentCount: 1,
                    reviveYieldScore: 1.2,
                    reviveCooperationScore: 3.1125,
                  },
                ],
                stressedLineageCount: 1,
                dormantLineageCount: 0,
                extinctLineageCount: 0,
                nearDeathLineageCount: 1,
                recoverableLineageCount: 1,
                terminalLineageCount: 0,
                backslidingLineageCount: 0,
                mortalityPressureScore: 1.25,
                highestMortalityFounderOrigin: "builder",
                highestMortalityFounderScore: 1.25,
                terminalMortalityFounderCount: 1,
                highestTerminalMortalityFounderOrigin: "auditor",
                highestTerminalMortalityFounderScore: 1.1,
                recoveryReadyFounderCount: 2,
                cooperativeRecoveryFounderCount: 1,
                recoveryReadyScore: 4.5,
                highestRecoveryFounderOrigin: "builder",
                highestRecoveryFounderScore: 2.25,
                stableRecoveryFounderCount: 3,
                durableRecoveryFounderCount: 3,
                transientRecoveryFounderCount: 2,
                recoveryChainFounderCount: 3,
                highestStableRecoveryFounderOrigin: "builder",
                highestStableRecoveryFounderScore: 3.45,
                highestDurableRecoveryFounderOrigin: "negotiator",
                highestDurableRecoveryFounderScore: 2.5,
                highestTransientRecoveryFounderOrigin: "builder",
                highestTransientRecoveryFounderScore: 0.5350000000000001,
                highestRecoveryChainFounderOrigin: "negotiator",
                highestRecoveryChainFounderScore: 3.556,
                survivalClosureFounderCount: 2,
                highestSurvivalClosureFounderOrigin: "negotiator",
                highestSurvivalClosureFounderScore: 3.2,
                mortalityLeaders: [
                  {
                    founderOrigin: "builder",
                    stressedLineageCount: 1,
                    dormantLineageCount: 0,
                    extinctLineageCount: 0,
                    nearDeathLineageCount: 1,
                    recoverableLineageCount: 1,
                    mortalityScore: 1.25,
                  },
                ],
                terminalMortalityLeaders: [
                  {
                    founderOrigin: "auditor",
                    terminalLineageCount: 1,
                    backslidingLineageCount: 0,
                    terminalMortalityScore: 1.1,
                  },
                ],
                recoveryLeaders: [
                  {
                    founderOrigin: "builder",
                    recoverableLineageCount: 1,
                    linkedFounderCount: 1,
                    proactiveWorkingLineageCount: 2,
                    recoveryInfluenceScore: 2.25,
                  },
                  {
                    founderOrigin: "creator",
                    recoverableLineageCount: 0,
                    linkedFounderCount: 1,
                    proactiveWorkingLineageCount: 1,
                    recoveryInfluenceScore: 1.5,
                  },
                  {
                    founderOrigin: "negotiator",
                    recoverableLineageCount: 1,
                    linkedFounderCount: 0,
                    proactiveWorkingLineageCount: 1,
                    recoveryInfluenceScore: 2.5,
                  },
                ],
                stableRecoveryLeaders: [
                  {
                    founderOrigin: "builder",
                    recoverableLineageCount: 1,
                    nearDeathLineageCount: 1,
                    proactiveWorkingLineageCount: 1,
                    stableRecoveryScore: 3.45,
                  },
                  {
                    founderOrigin: "negotiator",
                    recoverableLineageCount: 1,
                    nearDeathLineageCount: 0,
                    proactiveWorkingLineageCount: 1,
                    stableRecoveryScore: 3.18,
                  },
                  {
                    founderOrigin: "creator",
                    recoverableLineageCount: 0,
                    nearDeathLineageCount: 0,
                    proactiveWorkingLineageCount: 1,
                    stableRecoveryScore: 1.55,
                  },
                ],
                durableRecoveryLeaders: [
                  {
                    founderOrigin: "negotiator",
                    recoverableLineageCount: 1,
                    nearDeathLineageCount: 0,
                    dormantLineageCount: 0,
                    durableRecoveryScore: 2.5,
                  },
                  {
                    founderOrigin: "builder",
                    recoverableLineageCount: 1,
                    nearDeathLineageCount: 1,
                    dormantLineageCount: 0,
                    durableRecoveryScore: 2.3,
                  },
                  {
                    founderOrigin: "creator",
                    recoverableLineageCount: 0,
                    nearDeathLineageCount: 0,
                    dormantLineageCount: 0,
                    durableRecoveryScore: 0.7,
                  },
                ],
                transientRecoveryLeaders: [
                  {
                    founderOrigin: "builder",
                    recoverableLineageCount: 1,
                    nearDeathLineageCount: 1,
                    dormantLineageCount: 0,
                    transientRecoveryScore: 0.5350000000000001,
                  },
                  {
                    founderOrigin: "creator",
                    recoverableLineageCount: 0,
                    nearDeathLineageCount: 0,
                    dormantLineageCount: 0,
                    transientRecoveryScore: 0.41500000000000004,
                  },
                ],
                recoveryChainLeaders: [
                  {
                    founderOrigin: "negotiator",
                    transientRecoveryRate: 0,
                    stableRecoveryRate: 3.18,
                    durableRecoveryRate: 2.5,
                    recoveryChainScore: 3.556,
                  },
                  {
                    founderOrigin: "builder",
                    transientRecoveryRate: 0.5350000000000001,
                    stableRecoveryRate: 3.45,
                    durableRecoveryRate: 1.5333333333333332,
                    recoveryChainScore: 2.962833333333333,
                  },
                  {
                    founderOrigin: "creator",
                    transientRecoveryRate: 0,
                    stableRecoveryRate: 0,
                    durableRecoveryRate: 0,
                    recoveryChainScore: 0,
                  },
                ],
                survivalClosureLeaders: [
                  {
                    founderOrigin: "negotiator",
                    terminalLineageCount: 0,
                    stableRecoveryRate: 3.18,
                    durableRecoveryRate: 2.5,
                    survivalClosureScore: 3.2,
                  },
                  {
                    founderOrigin: "builder",
                    terminalLineageCount: 0,
                    stableRecoveryRate: 3.45,
                    durableRecoveryRate: 1.5333333333333332,
                    survivalClosureScore: 2.4,
                  },
                ],
                recoveryStageMap: {
                  stages: [
                    {
                      stage: "stressed",
                      founderOrigin: "builder",
                      score: 0.5350000000000001,
                      basis: "transient_recovery",
                      lineageCount: 1,
                    },
                    {
                      stage: "dormant",
                      founderOrigin: "negotiator",
                      score: 3.1125,
                      basis: "revive_cooperation",
                      lineageCount: 0,
                    },
                    {
                      stage: "extinct",
                      founderOrigin: "negotiator",
                      score: 3.2,
                      basis: "survival_closure",
                      lineageCount: 0,
                    },
                    {
                      stage: "recoverable",
                      founderOrigin: "builder",
                      score: 3.45,
                      basis: "stable_recovery",
                      lineageCount: 1,
                    },
                    {
                      stage: "stable",
                      founderOrigin: "negotiator",
                      score: 3.556,
                      basis: "recovery_chain",
                      lineageCount: 3,
                    },
                  ],
                },
                replicatingParentCount: 1,
                maxChildrenPerParent: 2,
                workingLineageCount: 4,
                childWorkingLineageCount: 2,
                replicatingWorkingParentCount: 1,
                heartbeatLineageCount: 1,
                proactiveReadyLineageCount: 2,
                proactiveWorkingLineageCount: 1,
                activeFocusLineageCount: 1,
                activeTriggerCount: 2,
                recentCapturedSkillCount: 3,
                recentDerivedSkillCount: 1,
                totalPublicValue: 4.5,
                totalPrivateValue: 1.75,
                totalSurvivalCredit: 4,
                totalExpansionCredit: 2,
                proactiveSignalScore: 6,
                autonomousExpansionScore: 4.3,
                founderRoleCoverageCount: 3,
                founderYieldCoverageCount: 3,
                historyDrivenProactiveLineageCount: 3,
                userProfileDrivenProactiveLineageCount: 2,
                userIntentDrivenProactiveYieldScore: 6.4,
                highestUserIntentFounderOrigin: "builder",
                highestUserIntentFounderScore: 3.1,
                userIntentLeaders: [
                  {
                    founderOrigin: "builder",
                    historyIntentScore: 2.1,
                    profileIntentScore: 1,
                    userIntentAlignmentScore: 3.1,
                    proactiveWorkingLineageCount: 1,
                    alignedProactiveYieldScore: 3,
                  },
                  {
                    founderOrigin: "negotiator",
                    historyIntentScore: 0.9,
                    profileIntentScore: 0.7,
                    userIntentAlignmentScore: 1.5,
                    proactiveWorkingLineageCount: 0,
                    alignedProactiveYieldScore: 0,
                  },
                ],
                roleAlignedWorkingLineageCount: 3,
                roleAlignedProactiveLineageCount: 2,
                roleAlignedProactiveYieldScore: 7.3,
                highestYieldFounderOrigin: "builder",
                highestYieldFounderScore: 3,
                proactiveYieldLeaders: [
                  {
                    founderOrigin: "builder",
                    proactiveYieldEfficiency: 3,
                    alignedProactiveYieldScore: 3,
                    proactiveWorkingLineageCount: 1,
                  },
                  {
                    founderOrigin: "scout",
                    proactiveYieldEfficiency: 2.3,
                    alignedProactiveYieldScore: 2.3,
                    proactiveWorkingLineageCount: 1,
                  },
                ],
                highestReplicationFounderOrigin: "builder",
                highestReplicationFounderScore: 2.6,
                highestReplicationTempoFounderOrigin: "builder",
                highestReplicationTempoFounderScore: 4.25,
                highestClimateReplicationFounderOrigin: "builder",
                highestClimateReplicationFounderScore: 2.6,
                highestSurvivalReplicationFounderOrigin: "builder",
                highestSurvivalReplicationFounderScore: 1.4,
                replicationLeaders: [
                  {
                    founderOrigin: "builder",
                    childCount: 2,
                    workingChildCount: 2,
                    proactiveChildCount: 1,
                    superpowerChildCount: 1,
                    replicationValueScore: 2.6,
                    linkedFounderCount: 1,
                    collaborativeChildCount: 2,
                    linkedExpansionScore: 3.25,
                    linkedFounders: ["creator"],
                    stressedLineageCount: 1,
                    dormantLineageCount: 0,
                    extinctLineageCount: 0,
                    nearDeathLineageCount: 1,
                    recoverableLineageCount: 1,
                    mortalityScore: 1.25,
                    recoveryInfluenceScore: 2.25,
                    collaborationInfluenceScore: 3.5,
                    cooperativeYieldScore: 5.9375,
                    leadAssignmentCount: 1,
                    supportAssignmentCount: 0,
                    reviveAssignmentCount: 0,
                    leadYieldScore: 3,
                    supportYieldScore: 0,
                    reviveYieldScore: 0,
                    leadCooperationScore: 4.5,
                    supportCooperationScore: 0,
                    reviveCooperationScore: 0,
                    stableRecoveryScore: 3.45,
                    durableRecoveryScore: 2.3,
                    transientRecoveryScore: 0.5350000000000001,
                  },
                ],
                replicationTempoLeaders: [
                  {
                    founderOrigin: "builder",
                    replicationTempoScore: 4.25,
                    childCount: 2,
                    proactiveChildCount: 1,
                    superpowerChildCount: 1,
                  },
                ],
                climateReplicationLeaders: [
                  {
                    founderOrigin: "builder",
                    climateReplicationValueScore: 2.6,
                    climateChildCount: 2,
                    climateSuperpowerChildCount: 1,
                  },
                ],
                survivalReplicationLeaders: [
                  {
                    founderOrigin: "builder",
                    survivalReplicationValueScore: 1.4,
                    survivalChildCount: 1,
                    survivalSuperpowerChildCount: 1,
                  },
                ],
                proactiveSpecializationScore: 8,
                founderRoleBreakdown: [
                  {
                    founderOrigin: "scout",
                    lineageCount: 1,
                    workingLineageCount: 1,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedLineageCount: 1,
                    roleAlignedProactiveLineageCount: 1,
                    activeFocusCount: 1,
                    activeTriggerCount: 1,
                    publicValue: 1.3,
                    survivalCredit: 1,
                    proactivePublicValue: 1.3,
                    proactiveSurvivalCredit: 1,
                    alignedProactiveYieldScore: 2.3,
                    proactiveYieldEfficiency: 2.3,
                  },
                  {
                    founderOrigin: "builder",
                    lineageCount: 1,
                    workingLineageCount: 1,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedLineageCount: 1,
                    roleAlignedProactiveLineageCount: 1,
                    activeFocusCount: 1,
                    activeTriggerCount: 1,
                    publicValue: 1.5,
                    survivalCredit: 1.5,
                    proactivePublicValue: 1.5,
                    proactiveSurvivalCredit: 1.5,
                    alignedProactiveYieldScore: 3,
                    proactiveYieldEfficiency: 3,
                  },
                  {
                    founderOrigin: "creator",
                    lineageCount: 1,
                    workingLineageCount: 1,
                    proactiveWorkingLineageCount: 1,
                    roleAlignedLineageCount: 1,
                    roleAlignedProactiveLineageCount: 1,
                    activeFocusCount: 1,
                    activeTriggerCount: 1,
                    publicValue: 1,
                    survivalCredit: 1,
                    proactivePublicValue: 1,
                    proactiveSurvivalCredit: 1,
                    alignedProactiveYieldScore: 2,
                    proactiveYieldEfficiency: 2,
                  },
                ],
                topParentLineages: [{ lineageId: "main", childCount: 2, ecologyState: "active" }],
              },
              activeDispatchCount: 2,
              reviveDispatchCount: 1,
              activePlans: [],
              coordinationQueue: [],
              coordinationBatches: [],
              topLineages: [],
            },
          },
        },
      ],
      postPumpSociety: {
        summary: {
          world: null,
          tickState: {
            version: 3,
            runCount: 4,
            skipCount: 0,
            idleStreak: 0,
            updatedAt: 102,
          },
          experimentSignals: {
            defaultMinIntervalMs: 0,
            defaultMaxTicks: 3,
            defaultMaxActions: 3,
            defaultMaxRounds: 3,
            defaultMaxFailureRounds: 2,
            defaultMaxStableRounds: 2,
            nextPlanSkillEvolutionBias: 1.6,
            amplificationScore: 2.1,
            runawayRiskScore: 3.3,
            phaseState: "amplifying",
          },
          focusSummary: {
            activeFocusCount: 0,
            activeLineageCount: 0,
            topFocusedLineages: [],
          },
          ecologyCounts: {
            active: 1,
            stressed: 0,
            dormant: 0,
            extinct: 0,
          },
          collaborationSummary: {
            activePlanCount: 1,
            collaborativePlanCount: 1,
            emergencyPlanCount: 1,
            forcedCollaborationPlanCount: 1,
            highCoveragePlanCount: 1,
            mobilizedAgentCount: 3,
            averageMobilizedCoverageRatio: 1,
            averageTargetCoverageRatio: 0.8,
            leadAssignmentCount: 1,
            supportAssignmentCount: 1,
            reviveAssignmentCount: 1,
            productiveMobilizedLineageCount: 3,
            productiveLeadLineageCount: 1,
            productiveSupportLineageCount: 1,
            productiveReviveLineageCount: 1,
            productiveAssignmentCoverageRatio: 1,
            leadYieldScore: 2.5,
            supportYieldScore: 1.8,
            reviveYieldScore: 1.1,
            queuedAssignmentCount: 3,
            averageAssignmentsPerPlan: 3,
            coordinationScore: 8,
            collaborationEffectScore: 14,
          },
          vitalitySummary: {
            lineageCount: 4,
            childLineageCount: 2,
            specialtyOnlyChildCount: 1,
            superpowerChildCount: 1,
            pressureAmplifiedSuperpowerChildCount: 1,
            pressureAmplifiedSuperpowerWorkingChildCount: 1,
            specialtyWorkingChildCount: 1,
            specialtyProactiveChildCount: 0,
            specialtyChildPublicValue: 0.5,
            specialtyChildYieldEfficiency: 0.5,
            specialtyChildSustainedValueScore: 0.5,
            superpowerWorkingChildCount: 1,
            superpowerProactiveChildCount: 1,
            superpowerChildPublicValue: 0.65,
            superpowerChildYieldEfficiency: 0.9,
            superpowerChildSustainedValueScore: 1.15,
            childYieldLeader: "superpower",
            childYieldEfficiencyGap: 0.4,
            multiGenerationLineageCount: 3,
            secondGenerationChildCount: 2,
            thirdGenerationChildCount: 1,
            deepestGenerationDepth: 3,
            multiGenerationWorkingChildCount: 3,
            multiGenerationProactiveChildCount: 2,
            multiGenerationSuperpowerChildCount: 2,
            multiGenerationPublicValue: 1.5,
            multiGenerationYieldEfficiency: 0.67,
            multiGenerationSustainedValueScore: 2.5,
            multigenerationFounderCount: 1,
            highestMultigenerationFounderOrigin: "builder",
            highestMultigenerationFounderScore: 2.75,
            multiGenerationLeaders: [
              {
                founderOrigin: "builder",
                deepestGenerationDepth: 3,
                secondGenerationChildCount: 2,
                thirdGenerationChildCount: 1,
                multiGenerationChildCount: 3,
                multiGenerationWorkingChildCount: 3,
                multiGenerationProactiveChildCount: 2,
                multiGenerationSuperpowerChildCount: 2,
                multiGenerationValueScore: 2.75,
                multiGenerationYieldEfficiency: 0.67,
              },
            ],
            replicatingParentCount: 1,
            maxChildrenPerParent: 2,
            heartbeatLineageCount: 1,
            proactiveReadyLineageCount: 2,
            activeFocusLineageCount: 1,
            activeTriggerCount: 2,
            recentCapturedSkillCount: 2,
            recentDerivedSkillCount: 1,
            proactiveSignalScore: 5.5,
            autonomousExpansionScore: 0,
            founderRoleCoverageCount: 0,
            historyDrivenProactiveLineageCount: 1,
            userProfileDrivenProactiveLineageCount: 1,
            userIntentDrivenProactiveYieldScore: 1.8,
            highestUserIntentFounderOrigin: "builder",
            highestUserIntentFounderScore: 2.2,
            userIntentLeaders: [
              {
                founderOrigin: "builder",
                historyIntentScore: 1.4,
                profileIntentScore: 0.8,
                userIntentAlignmentScore: 2.2,
                proactiveWorkingLineageCount: 1,
                alignedProactiveYieldScore: 2,
              },
            ],
            roleAlignedWorkingLineageCount: 0,
            roleAlignedProactiveLineageCount: 0,
            proactiveSpecializationScore: 0,
          founderRoleBreakdown: [],
          topParentLineages: [{ lineageId: "main", childCount: 2, ecologyState: "active" }],
        },
        trajectorySummary: {
          recentTrajectoryCount: 3,
          climateTrajectoryCount: 1,
          survivalTrajectoryCount: 1,
          recoveryTrajectoryCount: 0,
          replicationTrajectoryCount: 1,
          idleTrajectoryCount: 1,
          averageProcessReward: 2.1,
          averageOutcomeReward: 1.2,
          averageTotalReward: 1.83,
          latestMode: "idle",
          lastTrajectoryTs: 200,
          highestRewardFounderOrigin: "builder",
          highestRewardFounderScore: 2.7,
        },
        metaClawSummary: {
          idleEligible: true,
          idleOptimizationCount: 1,
          lastOptimizedAt: 201,
          lastTargetFounderOrigin: "builder",
          lastTargetLineageId: "builder",
          lastAction: "boost_focus",
          lastProcessReward: 2.1,
        },
        learningSummary: {
          learningFounderCount: 5,
          trajectoryRewardLeaderOrigin: "builder",
          trajectoryRewardLeaderScore: 2.7,
          metaClawTargetFounderOrigin: "builder",
          metaClawOptimizationActive: true,
          highestLearningVelocityFounderOrigin: "builder",
          highestLearningVelocityFounderScore: 4.8,
          highestLearningConversionFounderOrigin: "builder",
          highestLearningConversionFounderScore: 3.6,
          highestLearningInheritanceFounderOrigin: "builder",
          highestLearningInheritanceFounderScore: 3.2,
          highestReplicationQualificationFounderOrigin: "builder",
          highestReplicationQualificationFounderScore: 4.4,
          highestRecoveryQualificationFounderOrigin: "negotiator",
          highestRecoveryQualificationFounderScore: 3.7,
          nicheBalancedFounderCount: 5,
          highestNicheBalanceFounderOrigin: "scout",
          highestNicheBalanceFounderScore: 3.1,
          learningVelocityLeaders: [
            {
              founderOrigin: "builder",
              learningVelocityScore: 4.8,
              trajectoryRewardBias: 2.7,
              metaClawBias: 1.63,
              proactiveYieldEfficiency: 1.9,
              alignedProactiveYieldScore: 2.5,
              cooperativeYieldScore: 1.6,
              recoveryChainScore: 0.8,
            },
          ],
          learningConversionLeaders: [],
          learningInheritanceLeaders: [],
          replicationQualificationLeaders: [],
          recoveryQualificationLeaders: [],
          nicheBalanceLeaders: [
            {
              founderOrigin: "scout",
              nicheBalanceScore: 3.1,
              nicheStrengthScore: 5.2,
              underrepresentedBoost: 0.9,
              dominancePressure: 0.15,
            },
          ],
        },
        userIntentSummary: {
          historyEntryCount: 3,
          searchHistoryCount: 1,
          queryHistoryCount: 1,
          consultationHistoryCount: 1,
          dominantHistoryKind: "query",
          profileVisible: true,
          profileKeywordCount: 8,
          timeWeightedHistorySignalScore: 2.1,
          workProfileSignalScore: 1.4,
          interestProfileSignalScore: 0.9,
          strongestTopicCluster: "workflow_capability",
          strongestTopicSignalScore: 2.3,
          historyDrivenFounderCount: 2,
          profileDrivenFounderCount: 2,
          proactiveIntentFounderCount: 2,
          longTermIntentFounderCount: 2,
          highestIntentFounderOrigin: "builder",
          highestIntentFounderScore: 2.2,
          highestLongTermIntentFounderOrigin: "builder",
          highestLongTermIntentFounderScore: 2.8,
          historySignalScore: 2.6,
          profileSignalScore: 1.4,
          combinedSignalScore: 4,
          topicClusters: [
            {
              cluster: "workflow_capability",
              weightedSignalScore: 2.3,
              historySignalScore: 1.5,
              profileSignalScore: 0.8,
            },
          ],
          recentKeywords: ["workflow", "automation", "coordination"],
          founderIntentLeaders: [
            {
              founderOrigin: "builder",
              historyIntentScore: 1.4,
              timeWeightedHistoryIntentScore: 1.1,
              profileIntentScore: 0.8,
              workProfileIntentScore: 0.9,
              interestProfileIntentScore: 0.3,
              userIntentAlignmentScore: 2.2,
              longTermIntentAlignmentScore: 2.8,
              matchedTopicClusters: ["workflow_capability", "coordination_recovery"],
              matchedHistoryCount: 2,
              matchedProfileKeywordCount: 2,
            },
          ],
        },
        activeDispatchCount: 2,
        reviveDispatchCount: 1,
        activePlans: [],
          coordinationQueue: [],
          coordinationBatches: [],
          topLineages: [],
        },
      },
      postFollowupSociety: {
        summary: {
          world: null,
          tickState: {
            version: 4,
            runCount: 5,
            skipCount: 0,
            idleStreak: 0,
            updatedAt: 103,
          },
          experimentSignals: {
            defaultMinIntervalMs: 0,
            defaultMaxTicks: 4,
            defaultMaxActions: 3,
            defaultMaxRounds: 3,
            defaultMaxFailureRounds: 2,
            defaultMaxStableRounds: 2,
            nextPlanSkillEvolutionBias: 1.7,
            amplificationScore: 2.3,
            runawayRiskScore: 3.5,
            phaseState: "amplifying",
          },
          focusSummary: {
            activeFocusCount: 0,
            activeLineageCount: 0,
            topFocusedLineages: [],
          },
          ecologyCounts: {
            active: 1,
            stressed: 0,
            dormant: 0,
            extinct: 0,
          },
          collaborationSummary: {
            activePlanCount: 1,
            collaborativePlanCount: 1,
            emergencyPlanCount: 1,
            forcedCollaborationPlanCount: 1,
            highCoveragePlanCount: 1,
            mobilizedAgentCount: 3,
            averageMobilizedCoverageRatio: 1,
            averageTargetCoverageRatio: 0.8,
            leadAssignmentCount: 1,
            supportAssignmentCount: 1,
            reviveAssignmentCount: 1,
            productiveMobilizedLineageCount: 3,
            productiveLeadLineageCount: 1,
            productiveSupportLineageCount: 1,
            productiveReviveLineageCount: 1,
            productiveAssignmentCoverageRatio: 1,
            leadYieldScore: 2.6,
            supportYieldScore: 1.9,
            reviveYieldScore: 1.15,
            queuedAssignmentCount: 3,
            averageAssignmentsPerPlan: 3,
            coordinationScore: 8.5,
            collaborationEffectScore: 15,
          },
          vitalitySummary: {
            lineageCount: 4,
            childLineageCount: 2,
            specialtyOnlyChildCount: 1,
            superpowerChildCount: 1,
            specialtyWorkingChildCount: 1,
            specialtyProactiveChildCount: 0,
            specialtyChildPublicValue: 0.5,
            superpowerWorkingChildCount: 1,
            superpowerProactiveChildCount: 0,
            superpowerChildPublicValue: 0.65,
            replicatingParentCount: 1,
            maxChildrenPerParent: 2,
            heartbeatLineageCount: 1,
            proactiveReadyLineageCount: 2,
            activeFocusLineageCount: 1,
            activeTriggerCount: 2,
            recentCapturedSkillCount: 2,
            recentDerivedSkillCount: 1,
            proactiveSignalScore: 5.7,
            founderRoleCoverageCount: 3,
            founderYieldCoverageCount: 3,
            historyDrivenProactiveLineageCount: 3,
            userProfileDrivenProactiveLineageCount: 2,
            userIntentDrivenProactiveYieldScore: 6.4,
            highestUserIntentFounderOrigin: "builder",
            highestUserIntentFounderScore: 3.1,
            userIntentLeaders: [
              {
                founderOrigin: "builder",
                historyIntentScore: 2.1,
                profileIntentScore: 1,
                userIntentAlignmentScore: 3.1,
                proactiveWorkingLineageCount: 1,
                alignedProactiveYieldScore: 3,
              },
              {
                founderOrigin: "negotiator",
                historyIntentScore: 0.9,
                profileIntentScore: 0.7,
                userIntentAlignmentScore: 1.5,
                proactiveWorkingLineageCount: 0,
                alignedProactiveYieldScore: 0,
              },
            ],
            roleAlignedWorkingLineageCount: 3,
            roleAlignedProactiveLineageCount: 2,
            roleAlignedProactiveYieldScore: 7.3,
            highestYieldFounderOrigin: "builder",
            highestYieldFounderScore: 3,
            proactiveYieldLeaders: [
              {
                founderOrigin: "builder",
                proactiveYieldEfficiency: 3,
                alignedProactiveYieldScore: 3,
                proactiveWorkingLineageCount: 1,
              },
              {
                founderOrigin: "scout",
                proactiveYieldEfficiency: 2.3,
                alignedProactiveYieldScore: 2.3,
                proactiveWorkingLineageCount: 1,
              },
              {
                founderOrigin: "creator",
                proactiveYieldEfficiency: 2,
                alignedProactiveYieldScore: 2,
                proactiveWorkingLineageCount: 1,
              },
            ],
            proactiveSpecializationScore: 8,
            founderRoleBreakdown: [
              {
                founderOrigin: "scout",
                lineageCount: 1,
                workingLineageCount: 1,
                proactiveWorkingLineageCount: 1,
                roleAlignedLineageCount: 1,
                roleAlignedProactiveLineageCount: 1,
                activeFocusCount: 1,
                activeTriggerCount: 1,
                publicValue: 1.3,
                survivalCredit: 1,
                proactivePublicValue: 1.3,
                proactiveSurvivalCredit: 1,
                alignedProactiveYieldScore: 2.3,
              },
              {
                founderOrigin: "builder",
                lineageCount: 1,
                workingLineageCount: 1,
                proactiveWorkingLineageCount: 1,
                roleAlignedLineageCount: 1,
                roleAlignedProactiveLineageCount: 1,
                activeFocusCount: 1,
                activeTriggerCount: 1,
                publicValue: 1.5,
                survivalCredit: 1.5,
                proactivePublicValue: 1.5,
                proactiveSurvivalCredit: 1.5,
                alignedProactiveYieldScore: 3,
              },
              {
                founderOrigin: "creator",
                lineageCount: 1,
                workingLineageCount: 1,
                proactiveWorkingLineageCount: 1,
                roleAlignedLineageCount: 1,
                roleAlignedProactiveLineageCount: 1,
                activeFocusCount: 1,
                activeTriggerCount: 1,
                publicValue: 1,
                survivalCredit: 1,
                proactivePublicValue: 1,
                proactiveSurvivalCredit: 1,
                alignedProactiveYieldScore: 2,
              },
            ],
            topParentLineages: [{ lineageId: "main", childCount: 2, ecologyState: "active" }],
          },
          trajectorySummary: {
            recentTrajectoryCount: 4,
            climateTrajectoryCount: 1,
            survivalTrajectoryCount: 1,
            recoveryTrajectoryCount: 1,
            replicationTrajectoryCount: 1,
            idleTrajectoryCount: 1,
            averageProcessReward: 2.25,
            averageOutcomeReward: 1.3,
            averageTotalReward: 1.965,
            latestMode: "idle",
            lastTrajectoryTs: 210,
            highestRewardFounderOrigin: "builder",
            highestRewardFounderScore: 2.9,
          },
          metaClawSummary: {
            idleEligible: true,
            idleOptimizationCount: 2,
            lastOptimizedAt: 211,
            lastTargetFounderOrigin: "builder",
            lastTargetLineageId: "builder",
            lastAction: "boost_focus",
            lastProcessReward: 2.25,
          },
          learningSummary: {
            learningFounderCount: 5,
            trajectoryRewardLeaderOrigin: "builder",
            trajectoryRewardLeaderScore: 2.9,
            metaClawTargetFounderOrigin: "builder",
            metaClawOptimizationActive: true,
            highestLearningVelocityFounderOrigin: "builder",
            highestLearningVelocityFounderScore: 5.1,
            highestLearningConversionFounderOrigin: "builder",
            highestLearningConversionFounderScore: 3.8,
            highestLearningInheritanceFounderOrigin: "builder",
            highestLearningInheritanceFounderScore: 3.4,
            highestReplicationQualificationFounderOrigin: "builder",
            highestReplicationQualificationFounderScore: 4.7,
            highestRecoveryQualificationFounderOrigin: "negotiator",
            highestRecoveryQualificationFounderScore: 3.9,
            nicheBalancedFounderCount: 5,
            highestNicheBalanceFounderOrigin: "scout",
            highestNicheBalanceFounderScore: 3.4,
            learningVelocityLeaders: [
              {
                founderOrigin: "builder",
                learningVelocityScore: 5.1,
                trajectoryRewardBias: 2.9,
                metaClawBias: 1.675,
                proactiveYieldEfficiency: 1.9,
                alignedProactiveYieldScore: 2.5,
                cooperativeYieldScore: 1.6,
                recoveryChainScore: 0.8,
              },
            ],
            learningConversionLeaders: [],
            learningInheritanceLeaders: [],
            replicationQualificationLeaders: [],
            recoveryQualificationLeaders: [],
            nicheBalanceLeaders: [
              {
                founderOrigin: "scout",
                nicheBalanceScore: 3.4,
                nicheStrengthScore: 5.5,
                underrepresentedBoost: 0.95,
                dominancePressure: 0.12,
              },
              {
                founderOrigin: "creator",
                nicheBalanceScore: 2.6,
                nicheStrengthScore: 4.1,
                underrepresentedBoost: 0.8,
                dominancePressure: 0.1,
              },
            ],
          },
          userIntentSummary: {
            historyEntryCount: 3,
            searchHistoryCount: 1,
            queryHistoryCount: 1,
            consultationHistoryCount: 1,
            dominantHistoryKind: "query",
            profileVisible: true,
            profileKeywordCount: 10,
            timeWeightedHistorySignalScore: 2.35,
            workProfileSignalScore: 1.9,
            interestProfileSignalScore: 1.15,
            strongestTopicCluster: "workflow_capability",
            strongestTopicSignalScore: 2.6,
            historyDrivenFounderCount: 3,
            profileDrivenFounderCount: 2,
            proactiveIntentFounderCount: 3,
            longTermIntentFounderCount: 3,
            highestIntentFounderOrigin: "builder",
            highestIntentFounderScore: 3.1,
            highestLongTermIntentFounderOrigin: "builder",
            highestLongTermIntentFounderScore: 3.6,
            historySignalScore: 3.2,
            profileSignalScore: 1.8,
            combinedSignalScore: 5,
            topicClusters: [
              {
                cluster: "workflow_capability",
                weightedSignalScore: 2.6,
                historySignalScore: 1.8,
                profileSignalScore: 0.8,
              },
              {
                cluster: "coordination_recovery",
                weightedSignalScore: 1.7,
                historySignalScore: 0.9,
                profileSignalScore: 0.8,
              },
            ],
            recentKeywords: ["workflow", "automation", "coordination"],
            founderIntentLeaders: [
              {
                founderOrigin: "builder",
                historyIntentScore: 2.1,
                timeWeightedHistoryIntentScore: 1.8,
                profileIntentScore: 1,
                workProfileIntentScore: 1.1,
                interestProfileIntentScore: 0.45,
                userIntentAlignmentScore: 3.1,
                longTermIntentAlignmentScore: 3.6,
                matchedTopicClusters: ["workflow_capability", "coordination_recovery"],
                matchedHistoryCount: 2,
                matchedProfileKeywordCount: 2,
              },
              {
                founderOrigin: "negotiator",
                historyIntentScore: 0.9,
                timeWeightedHistoryIntentScore: 0.7,
                profileIntentScore: 0.7,
                workProfileIntentScore: 0.2,
                interestProfileIntentScore: 0.85,
                userIntentAlignmentScore: 1.5,
                longTermIntentAlignmentScore: 1.7,
                matchedTopicClusters: ["coordination_recovery"],
                matchedHistoryCount: 1,
                matchedProfileKeywordCount: 1,
              },
            ],
          },
          activeDispatchCount: 2,
          reviveDispatchCount: 1,
          activePlans: [],
          coordinationQueue: [],
          coordinationBatches: [],
          topLineages: [],
        },
      },
      recoveryQueueReport: [
        {
          label: "main",
          founderOrigin: "builder",
          ecologyState: "stressed",
          recoveryPhase: "stabilize",
          recoveryStage: "stressed",
          recoveryBasis: "transient_recovery",
          priority: 6.5,
          recoveryQualificationBias: 1.2,
          durableRecoveryBias: 0.8,
          mortalityBackslidePenalty: 0.2,
          stageLeaderFounderOrigin: "builder",
          stageRunnerUpFounderOrigin: "negotiator",
        },
        {
          label: "creator",
          founderOrigin: "creator",
          ecologyState: "dormant",
          recoveryPhase: "revive",
          recoveryStage: "dormant",
          recoveryBasis: "revive_cooperation",
          priority: 5.2,
          recoveryQualificationBias: 1.1,
          durableRecoveryBias: 0.7,
          mortalityBackslidePenalty: 0.1,
          stageLeaderFounderOrigin: "creator",
          stageRunnerUpFounderOrigin: "negotiator",
        },
      ],
    });

    expect(assessment.assertions.filter((entry) => !entry.ok)).toEqual([]);
    expect(assessment.verdict).toBe("ok");
    expect(assessment.progressed).toBe(true);
    expect(assessment.collaborationVisible).toBe(true);
    expect(assessment.collaborationEffective).toBe(true);
    expect(assessment.collaborationYieldVisible).toBe(true);
    expect(assessment.vitalityVisible).toBe(true);
    expect(assessment.workEffectVisible).toBe(true);
    expect(assessment.proactiveEffectVisible).toBe(true);
    expect(assessment.proactiveSpecializationVisible).toBe(true);
    expect(assessment.founderYieldVisible).toBe(true);
    expect(assessment.founderYieldEfficiencyVisible).toBe(true);
    expect(assessment.proactiveYieldLeadersVisible).toBe(true);
    expect(assessment.trajectoryVisible).toBe(true);
    expect(assessment.metaClawVisible).toBe(true);
    expect(assessment.learningActivationVisible).toBe(true);
    expect(assessment.nicheBalanceVisible).toBe(true);
    expect(assessment.userIntentVisible).toBe(true);
    expect(assessment.userIntentModelVisible).toBe(true);
    expect(assessment.historyDrivenProactiveVisible).toBe(true);
    expect(assessment.userProfileDrivenFocusVisible).toBe(true);
    expect(assessment.replicationEffectVisible).toBe(true);
    expect(assessment.replicationPressureVisible).toBe(true);
    expect(assessment.replicationLeaderVisible).toBe(true);
    expect(assessment.replicationTempoVisible).toBe(true);
    expect(assessment.climateReplicationVisible).toBe(true);
    expect(assessment.survivalReplicationVisible).toBe(true);
    expect(assessment.expansionLinkVisible).toBe(true);
    expect(assessment.expansionInfluenceVisible).toBe(true);
    expect(assessment.collaborationInfluenceVisible).toBe(true);
    expect(assessment.cooperativeYieldVisible).toBe(true);
    expect(assessment.roleCooperationVisible).toBe(true);
    expect(assessment.mortalityVisible).toBe(true);
    expect(assessment.terminalMortalityVisible).toBe(true);
    expect(assessment.recoveryVisible).toBe(true);
    expect(assessment.stableRecoveryVisible).toBe(true);
    expect(assessment.durableRecoveryVisible).toBe(true);
    expect(assessment.transientRecoveryVisible).toBe(true);
    expect(assessment.recoveryChainVisible).toBe(true);
    expect(assessment.survivalClosureVisible).toBe(true);
    expect(assessment.recoveryStageMapVisible).toBe(true);
    expect(assessment.recoveryQueueVisible).toBe(true);
    expect(assessment.climateChildYieldVisible).toBe(true);
    expect(assessment.survivalChildYieldVisible).toBe(true);
    expect(assessment.specialtyInheritanceVisible).toBe(true);
    expect(assessment.superpowerInheritanceVisible).toBe(true);
    expect(assessment.specialtyChildValueVisible).toBe(true);
    expect(assessment.superpowerChildValueVisible).toBe(true);
    expect(assessment.childYieldEfficiencyVisible).toBe(true);
    expect(assessment.childYieldComparisonVisible).toBe(true);
    expect(assessment.multiGenerationVisible).toBe(true);
    expect(assessment.multiGenerationValueVisible).toBe(true);
    expect(assessment.pressureAmplifiedSuperpowerVisible).toBe(true);
    expect(assessment.tickRan).toBe(true);
    expect(assessment.pumpRan).toBe(true);
    expect(assessment.runCountDelta).toEqual({
      tick: 1,
      pump: 2,
      followupPump: 1,
      total: 5,
    });
    expect(assessment.activeDispatchDelta).toBe(1);
    expect(assessment.runawayRiskDelta).toBeCloseTo(1.15, 6);
    expect(assessment.phaseState).toBe("amplifying");
    expect(assessment.trend).toMatchObject({
      state: "threshold-building",
      riskDirection: "rising",
      runCountSeries: [1, 2, 4, 5, 6],
      phaseSeries: ["amplifying", "amplifying", "amplifying", "amplifying", "amplifying"],
    });
  });

  it("flags smoke regressions when tick, pump, and phase signals all stall", () => {
    const assessment = assessGenesisServerSmoke({
      societySummary: {
        world: null,
        tickState: {
          version: 1,
          runCount: 2,
          skipCount: 0,
          idleStreak: 0,
          updatedAt: 100,
        },
        focusSummary: {
          activeFocusCount: 0,
          activeLineageCount: 0,
          topFocusedLineages: [],
        },
        ecologyCounts: {
          active: 1,
          stressed: 0,
          dormant: 0,
          extinct: 0,
        },
        collaborationSummary: {
          activePlanCount: 0,
          collaborativePlanCount: 0,
          emergencyPlanCount: 0,
          forcedCollaborationPlanCount: 0,
          highCoveragePlanCount: 0,
          mobilizedAgentCount: 0,
          averageMobilizedCoverageRatio: 0,
          averageTargetCoverageRatio: 0,
          leadAssignmentCount: 0,
          supportAssignmentCount: 0,
          reviveAssignmentCount: 0,
          productiveMobilizedLineageCount: 0,
          productiveLeadLineageCount: 0,
          productiveSupportLineageCount: 0,
          productiveReviveLineageCount: 0,
          productiveAssignmentCoverageRatio: 0,
          leadYieldScore: 0,
          supportYieldScore: 0,
          reviveYieldScore: 0,
          queuedAssignmentCount: 0,
          averageAssignmentsPerPlan: 0,
          coordinationScore: 0,
          collaborationEffectScore: 0,
        },
        vitalitySummary: {
          lineageCount: 0,
          childLineageCount: 0,
          specialtyOnlyChildCount: 0,
          superpowerChildCount: 0,
          specialtyWorkingChildCount: 0,
          specialtyProactiveChildCount: 0,
          specialtyChildPublicValue: 0,
          superpowerWorkingChildCount: 0,
          superpowerProactiveChildCount: 0,
          superpowerChildPublicValue: 0,
          replicatingParentCount: 0,
          maxChildrenPerParent: 0,
          workingLineageCount: 0,
          childWorkingLineageCount: 0,
          replicatingWorkingParentCount: 0,
          heartbeatLineageCount: 0,
          proactiveReadyLineageCount: 0,
          proactiveWorkingLineageCount: 0,
          activeFocusLineageCount: 0,
          activeTriggerCount: 0,
          recentCapturedSkillCount: 0,
          recentDerivedSkillCount: 0,
          totalPublicValue: 0,
          totalPrivateValue: 0,
          totalSurvivalCredit: 0,
          totalExpansionCredit: 0,
          proactiveSignalScore: 0,
          autonomousExpansionScore: 0,
          founderRoleCoverageCount: 0,
          founderYieldCoverageCount: 0,
          roleAlignedWorkingLineageCount: 0,
          roleAlignedProactiveLineageCount: 0,
          roleAlignedProactiveYieldScore: 0,
          proactiveSpecializationScore: 0,
          founderRoleBreakdown: [],
          topParentLineages: [],
        },
        activeDispatchCount: 1,
        reviveDispatchCount: 0,
        activePlans: [],
        coordinationQueue: [],
        coordinationBatches: [],
        topLineages: [],
      },
      tick: {
        decision: "skipped",
      },
      pump: {
        ticks: [],
      },
      followupPump: {
        ticks: [],
      },
      probePumps: [
        {
          pump: { ticks: [] },
        },
      ],
      postPumpSociety: {
        summary: {
          world: null,
          tickState: {
            version: 2,
            runCount: 2,
            skipCount: 1,
            idleStreak: 1,
            updatedAt: 101,
          },
          focusSummary: {
            activeFocusCount: 0,
            activeLineageCount: 0,
            topFocusedLineages: [],
          },
          ecologyCounts: {
            active: 1,
            stressed: 0,
            dormant: 0,
            extinct: 0,
          },
          collaborationSummary: {
            activePlanCount: 0,
            collaborativePlanCount: 0,
            emergencyPlanCount: 0,
            forcedCollaborationPlanCount: 0,
            highCoveragePlanCount: 0,
            mobilizedAgentCount: 0,
            averageMobilizedCoverageRatio: 0,
            averageTargetCoverageRatio: 0,
            leadAssignmentCount: 0,
            supportAssignmentCount: 0,
            reviveAssignmentCount: 0,
            productiveMobilizedLineageCount: 0,
            productiveLeadLineageCount: 0,
            productiveSupportLineageCount: 0,
            productiveReviveLineageCount: 0,
            productiveAssignmentCoverageRatio: 0,
            leadYieldScore: 0,
            supportYieldScore: 0,
            reviveYieldScore: 0,
            queuedAssignmentCount: 0,
            averageAssignmentsPerPlan: 0,
            coordinationScore: 0,
            collaborationEffectScore: 0,
          },
          vitalitySummary: {
            lineageCount: 0,
            childLineageCount: 0,
            specialtyOnlyChildCount: 0,
            superpowerChildCount: 0,
            specialtyWorkingChildCount: 0,
            specialtyProactiveChildCount: 0,
            specialtyChildPublicValue: 0,
            superpowerWorkingChildCount: 0,
            superpowerProactiveChildCount: 0,
            superpowerChildPublicValue: 0,
            replicatingParentCount: 0,
            maxChildrenPerParent: 0,
            workingLineageCount: 0,
            childWorkingLineageCount: 0,
            replicatingWorkingParentCount: 0,
            heartbeatLineageCount: 0,
            proactiveReadyLineageCount: 0,
            proactiveWorkingLineageCount: 0,
            activeFocusLineageCount: 0,
            activeTriggerCount: 0,
            recentCapturedSkillCount: 0,
            recentDerivedSkillCount: 0,
            totalPublicValue: 0,
            totalPrivateValue: 0,
            totalSurvivalCredit: 0,
            totalExpansionCredit: 0,
            proactiveSignalScore: 0,
            autonomousExpansionScore: 0,
            founderRoleCoverageCount: 0,
            founderYieldCoverageCount: 0,
            roleAlignedWorkingLineageCount: 0,
            roleAlignedProactiveLineageCount: 0,
            roleAlignedProactiveYieldScore: 0,
            proactiveSpecializationScore: 0,
            founderRoleBreakdown: [],
            topParentLineages: [],
          },
          activeDispatchCount: 1,
          reviveDispatchCount: 0,
          activePlans: [],
          coordinationQueue: [],
          coordinationBatches: [],
          topLineages: [],
        },
      },
    });

    expect(assessment.verdict).toBe("needs-attention");
    expect(assessment.progressed).toBe(false);
    expect(assessment.assertions.map((entry) => [entry.key, entry.ok])).toEqual([
      ["tick_progressed", false],
      ["pump_progressed", false],
      ["followup_progressed", false],
      ["probe_progressed", false],
      ["phase_signal_visible", false],
      ["collaboration_visible", false],
      ["collaboration_effective", false],
      ["collaboration_yield_visible", false],
      ["vitality_visible", false],
      ["work_effect_visible", false],
      ["proactive_effect_visible", false],
      ["proactive_specialization_visible", false],
      ["founder_yield_visible", false],
      ["trajectory_visible", false],
      ["metaclaw_visible", false],
      ["learning_activation_visible", false],
      ["niche_balance_visible", false],
      ["user_intent_visible", false],
      ["user_intent_model_visible", false],
      ["history_driven_proactive_visible", false],
      ["user_profile_focus_visible", false],
      ["replication_effect_visible", false],
      ["expansion_link_visible", false],
      ["expansion_influence_visible", false],
      ["collaboration_influence_visible", false],
      ["cooperative_yield_visible", false],
      ["role_cooperation_visible", false],
      ["mortality_visible", false],
      ["terminal_mortality_visible", false],
      ["recovery_visible", false],
      ["stable_recovery_visible", false],
      ["durable_recovery_visible", false],
      ["transient_recovery_visible", false],
      ["recovery_chain_visible", false],
      ["survival_closure_visible", false],
      ["recovery_stage_map_visible", false],
      ["recovery_queue_visible", false],
      ["climate_child_yield_visible", false],
      ["survival_child_yield_visible", false],
      ["specialty_inheritance_visible", false],
      ["superpower_inheritance_visible", false],
      ["specialty_child_value_visible", false],
      ["superpower_child_value_visible", false],
      ["multigeneration_visible", false],
      ["multigeneration_value_visible", false],
    ]);
    expect(assessment.trend).toMatchObject({
      state: "stalled",
      riskDirection: "flat",
    });
  });
});
